In [1]:
# Import useful libs:
import numpy as np 
import sys

In [3]:
# Get the array dimensions:
print("Dimensions:")
dim = int(input("Insert number o variables of the system:"))
print(str(dim) + "," + str(dim))
#Get the round rule for the problem:
digits = int(input("Insert the number of digits after the decimal points:"))
print("Digits after the decimal points:")
print(digits)

Dimensions:
3,3
Digits after the decimal points:
3


In [4]:
# Create empty arrays:
    # Input arrays:
AB = np.zeros((dim,dim+1))
    # Output arrays:
print(AB)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
# Fill the arrays:
print("Fill the weights:")
for i in range(0,dim):
    print("Collum "+str(i))
    for j in range(0, dim):
        AB[i][j] = float(input("Enter value in position ("+str(i)+","+str(j)+")"))
for i in range(0,dim):
    AB[i][3] = float(input("Enter value in position ("+str(i)+","+str(3)+")"))
print("AB =")
print(AB)

Fill the weights:
Collum 0
Collum 1
Collum 2
AB =
[[  1.   2.  -2. -15.]
 [  2.   1.  -5. -21.]
 [  1.  -4.   1.  18.]]


In [17]:
# Get pivot value and row:
for i in range(0, dim):
    pivot = abs(AB[i][i])
    pivot_row = i
    for j in range(i+1, dim):
        if abs(AB[j][i]) > pivot:
            pivot = abs(AB[j][i])
            print(AB[j][i])
            pivot_row = j
    print("The pivot for the current iteration is "+str(pivot))
# If actual row isn't the same as the pivot row, swap them up
    if i != pivot_row:
        AB[[i, pivot_row]] = AB[[pivot_row, i]]
        pivot_row = i
        print("We have swapped lines. The system now looks like this:")
        print("AB=" + str(AB))    
# Turn all the column of the  rows below in zero:
    for k in range(i + 1, dim):
        M = -round(AB[k][i] / AB[i][i],digits)
        for j in range(i, dim + 1):
            if i == j:
                AB[k][j] = 0
            else:
                AB[k][j] += round(M * AB[i][j], digits)
        print(AB) 

2.0
The pivot for the current iteration is 2.0
We have swapped lines. The system now looks like this:
AB=[[  2.   1.  -5. -21.]
 [  1.   2.  -2. -15.]
 [  1.  -4.   1.  18.]]
[[  2.    1.   -5.  -21. ]
 [  0.    1.5   0.5  -4.5]
 [  1.   -4.    1.   18. ]]
[[  2.    1.   -5.  -21. ]
 [  0.    1.5   0.5  -4.5]
 [  0.   -4.5   3.5  28.5]]
-4.5
The pivot for the current iteration is 4.5
We have swapped lines. The system now looks like this:
AB=[[  2.    1.   -5.  -21. ]
 [  0.   -4.5   3.5  28.5]
 [  0.    1.5   0.5  -4.5]]
[[  2.      1.     -5.    -21.   ]
 [  0.     -4.5     3.5    28.5  ]
 [  0.      0.      1.666   4.99 ]]
The pivot for the current iteration is 1.666


In [18]:
# Calculate the value of the x's:
x = [0 for i in range(dim)]
for i in range(dim - 1, -1, -1):
    x[i] = round(AB[i][dim] / AB[i][i], digits)
    for k in range(i - 1, -1, -1):
        AB[k][dim] -= round(AB[k][i] * x[i], digits)
print("x = " + str(x))

x = [-1.011, -4.004, 2.995]
