In [7]:
# Import useful libs:
import numpy as np 
import sys

In [8]:
# Get the array dimensions:
print("Dimensions:")
dim = int(input("Insert number o variables of the system:"))
print(str(dim) + "," + str(dim))
#Get the round rule for the problem:
 

Dimensions:
3,3


In [9]:
# Create empty arrays:
    # Input arrays:
A = np.zeros((dim,dim))
B = np.zeros((dim,1))
    # Output arrays:
U = np.zeros((dim,dim))
Y = np.zeros((dim,1))
print(A)
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.]
 [0.]
 [0.]]


In [34]:
# Fill the arrays:
print("Fill the weights:")
for i in range(0,dim):
    print("Collum "+str(i))
    for j in range(0, dim):
        A[i][j] = input("Enter value in position ("+str(i)+","+str(j)+")")
print("A =")
print(A)
for i in range(0,dim):
    B[i][0] = input("Enter value in position ("+str(i)+","+str(0)+")")
print("B=")
print(B)

Fill the weights:
Collum 0
Collum 1
Collum 2
A =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
B=
[[10.]
 [11.]
 [12.]]


In [45]:
for j in range(0, dim):
    pivot = 0
    # Get the pivot for the current iteration:
    for i in range(0, dim):
        if pivot < A[i][j]:
            pivot = A[i][j]
    # If pivot isn't in the first line, swap them
    print("The pivot of the current iteration is: "+str(pivot))
    if pivot != A[j][j]:
        for a in range(0, dim):
            if pivot == A[a][j]:
                A[[a,j]] = A[[j,a]]
                B[[a,j]] = B[[j,a]]
                # print(A)
                # print(B)
                break
    M = []
    # Calculate m:
    for a in range(j+1, dim):
        if a == j+1:
            M = []
        if A[a][j] == 0:
            M.append = 0
        else:
            M.append(- A[a][j]/pivot)


The pivot of the current iteration is: 7.0
[49. 56. 63.]
[56. 64. 72.]
[63. 72. 81.]
[28. 35. 42.]
[32. 40. 48.]
[36. 45. 54.]
[ 7. 14. 21.]
[ 8. 16. 24.]
[ 9. 18. 27.]
The pivot of the current iteration is: 8.0
[28. 35. 42.]
[32. 40. 48.]
[36. 45. 54.]
[49. 56. 63.]
[56. 64. 72.]
[63. 72. 81.]
[ 7. 14. 21.]
[ 8. 16. 24.]
[ 9. 18. 27.]
The pivot of the current iteration is: 9.0
[28. 35. 42.]
[32. 40. 48.]
[36. 45. 54.]
[ 7. 14. 21.]
[ 8. 16. 24.]
[ 9. 18. 27.]
[49. 56. 63.]
[56. 64. 72.]
[63. 72. 81.]
