In [7]:
# Import useful libs:
import numpy as np 
import sys

In [8]:
# Get the array dimensions:
print("Dimensions:")
dim = int(input("Insert number o variables of the system:"))
print(str(dim) + "," + str(dim))
#Get the round rule for the problem:
 

Dimensions:
3,3


In [83]:
# Create empty arrays:
    # Input arrays:
AB = np.zeros((dim,dim+1))
    # Output arrays:
print(AB)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [124]:
# Fill the arrays:
print("Fill the weights:")
for i in range(0,dim):
    print("Collum "+str(i))
    for j in range(0, dim):
        AB[i][j] = input("Enter value in position ("+str(i)+","+str(j)+")")
for i in range(0,dim):
    AB[i][3] = input("Enter value in position ("+str(i)+","+str(3)+")")
print("AB =")
print(AB)

Fill the weights:
Collum 0
Collum 1
Collum 2
AB =
[[ 1.  2.  3. 10.]
 [ 4.  5.  6. 11.]
 [ 7.  8.  9. 12.]]


In [125]:
# Get pivot value and row:
for i in range(0, dim):
    pivot = abs(AB[i][i])
    pivot_row = i
    for j in range(i+1, dim):
        if abs(AB[j][i]) > pivot:
            pivot = abs(AB[j][i])
            print(AB[j][i])
            pivot_row = j
    print("The pivot for the current iteration is "+str(pivot))
# If actual row isn't the same as the pivot row, swap them up
    if i != pivot_row:
        AB[[i, pivot_row]] = AB[[pivot_row, i]]
        pivot_row = i
        print("We have swapped lines. The system now looks like this:")
        print("AB=" + str(AB))    
# Turn all the column of the  rows below in zero:
    for k in range(i + 1, dim):
        M = -AB[k][i] / AB[i][i]
        for j in range(i, dim + 1):
            if i == j:
                AB[k][j] = 0
            else:
                AB[k][j] += M * AB[i][j]
        print(AB) 

4.0
7.0
The pivot for the current iteration is 7.0
We have swapped lines. The system now looks like this:
AB=[[ 7.  8.  9. 12.]
 [ 4.  5.  6. 11.]
 [ 1.  2.  3. 10.]]
[[ 7.          8.          9.         12.        ]
 [ 0.          0.42857143  0.85714286  4.14285714]
 [ 1.          2.          3.         10.        ]]
[[ 7.          8.          9.         12.        ]
 [ 0.          0.42857143  0.85714286  4.14285714]
 [ 0.          0.85714286  1.71428571  8.28571429]]
0.8571428571428572
The pivot for the current iteration is 0.8571428571428572
We have swapped lines. The system now looks like this:
AB=[[ 7.          8.          9.         12.        ]
 [ 0.          0.85714286  1.71428571  8.28571429]
 [ 0.          0.42857143  0.85714286  4.14285714]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00  1.20000000e+01]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00  8.28571429e+00]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16 -1.77635684e-15]]
The pivot for the current iteratio

In [130]:
# Calculate the value of the x's:
x = [0 for i in range(dim)]
for i in range(dim - 1, -1, -1):
    x[i] = AB[i][dim] / AB[i][i]
    for k in range(i - 1, -1, -1):
        AB[k][dim] -= AB[k][i] * x[i]
print(x)

[-25.333333333333332, 41.666666666666664, -16.0]
