In [1]:
# Import relevant libs
import numpy as np 
import sys

In [2]:
# Get the array dimensions:
print("Dimensions:")
dim = int(input("Insert number o variables of the system:"))
print(str(dim) + "," + str(dim))
#Get the round rule for the problem:
digits = int(input("Insert the number of digits after the decimal points:"))
print("Digits after the decimal points:")
print(digits)

Dimensions:
3,3
Digits after the decimal points:
3


In [34]:
# Create the necessary arrays, all of the them empty:
P = np.zeros((dim,dim))
A = np.zeros((dim,dim))
L = np.zeros((dim,dim))
U = np.zeros((dim,dim))
# Fill the P and A arrays:
for i in range(0, dim):
    P[i][i] = 1
P = np.rot90(P,1,(0,1))
print("P = " + str(P))
for i in range(0, dim):
    for j in range(0,dim):
        A[i][j] = float(input("Enter value in position ("+str(i)+","+str(j)+")"))
print("A = " + str(A))

P = [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
A = [[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]


In [36]:
for i in range(dim):
 
        # Upper Triangular
        for k in range(i, dim):
            operation_literal = ""
            # Summation of L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += round(L[i][j] * U[j][k],digits)
                operation_literal += "("+str(L[i][j])+"*"+str(U[j][k])+")"
                if j != i-1:
                    operation_literal += "+"
            print("The sum of L[i][j]*U[j][k] is defined by:")
            print(operation_literal + " = " + str(sum))
            # Evaluating U(i, k)
            U[i][k] = A[i][k] - sum
            print("U[" + str(i) + "][" + str(k) + "] = A["+str(i)+"]["+str(k)+"] - sum = " + str(U[i][k]))
        # Lower Triangular
        for k in range(i, dim):
            if (i == k):
                L[i][i] = 1  # Diagonal as 1
            else:
 
                # Summation of L(k, j) * U(j, i)
                sum = 0
                operation_literal = ""
                for j in range(i):
                    sum += round(L[k][j] * U[j][i], digits)
                    operation_literal += "("+str(L[i][j])+"*"+str(U[j][k])+")"
                    if j != i-1:
                        operation_literal += "+"
                print("The sum of L[i][j]*U[j][k] is defined by:")
                print(operation_literal + " = " + str(sum))
                # Evaluating L(k, i)
                L[k][i] = round(round(A[k][i] - sum, digits) / U[i][i], digits)
                print("L[" + str(k) + "][" + str(i) + "] = (A["+str(i)+"]["+str(k)+"] - sum)/U["+str(i)+"]["+str(i)+"]= " + str(L[k][i]))
            print("U=")
            print(U)
            print("L=")
            print(L)
        


The sum of L[i][j]*U[j][k] is defined by:
 = 0
U[0][0] = A[0][0] - sum = 2.0
The sum of L[i][j]*U[j][k] is defined by:
 = 0
U[0][1] = A[0][1] - sum = -1.0
The sum of L[i][j]*U[j][k] is defined by:
 = 0
U[0][2] = A[0][2] - sum = -2.0
U=
[[ 2. -1. -2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
L=
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The sum of L[i][j]*U[j][k] is defined by:
 = 0
L[1][0] = (A[0][1] - sum)/U[0][0]= -2.0
U=
[[ 2. -1. -2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
L=
[[ 1.  0.  0.]
 [-2.  0.  0.]
 [ 0.  0.  0.]]
The sum of L[i][j]*U[j][k] is defined by:
 = 0
L[2][0] = (A[0][2] - sum)/U[0][0]= -2.0
U=
[[ 2. -1. -2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
L=
[[ 1.  0.  0.]
 [-2.  0.  0.]
 [-2.  0.  0.]]
The sum of L[i][j]*U[j][k] is defined by:
(-2.0*-1.0) = 2.0
U[1][1] = A[1][1] - sum = 4.0
The sum of L[i][j]*U[j][k] is defined by:
(-2.0*-2.0) = 4.0
U[1][2] = A[1][2] - sum = -1.0
U=
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  0.]]
L=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2.  0.  0.]]
The sum of L[i][j]*U[j][k] is

In [37]:
 # setw is for displaying nicely
print("Lower Triangular\t\tUpper Triangular")

# Displaying the result :
for i in range(dim):

    # Lower
    for j in range(dim):
        print(L[i][j], end="\t")
    print("", end="\t")

    # Upper
    for j in range(dim):
        print(U[i][j], end="\t")
    print("")

Lower Triangular		Upper Triangular
1.0	0.0	0.0		2.0	-1.0	-2.0	
-2.0	1.0	0.0		0.0	4.0	-1.0	
-2.0	-1.0	1.0		0.0	0.0	3.0	
