In [1]:
# Import useful libs:
import numpy as np 
import sys

In [2]:
# Get the array dimensions:
print("Dimensions:")
dim = int(input("Insert number o variables of the system:"))
print(str(dim) + "," + str(dim))
#Get the round rule for the problem:
digits = int(input("Insert the number of digits after the decimal points:"))
print("Digits after the decimal points:")
print(digits)

Dimensions:
4,4
Digits after the decimal points:
4


In [3]:
# Create input and output
A = np.zeros((dim,dim))
L = np.zeros((dim,dim))

In [4]:
# Fill the A array:
for i in range(0, dim):
    for j in range(0,dim):
        A[i][j] = float(input("Enter value in position ("+str(i)+","+str(j)+")"))
print("A = " + str(A))

A = [[ 9.  3.  3.  4.]
 [ 3. 17. 10.  5.]
 [ 3. 10. 11.  4.]
 [ 4.  5.  4. 13.]]


In [5]:
def symmetric(array):
    x,y = array.shape
    if x != y:
        return False
    else:
        for i in range (0,x):
            for j in range (0,y):
                if A[i][j] != A[j][i]:
                    return False
    return True
positive = np.linalg.eigvals(A)
print(positive)
if np.all(positive > 0) and symmetric(A):
    print("True")
else:
    print("False")

[28.82792637 11.11637501  6.57999792  3.47570071]
True


In [7]:
# Decomposing a matrix
# into Lower Triangular
for i in range(dim):
    for j in range(i + 1):
        sum1 = 0
        # sum1mation for diagnols
        if j == i:
            operation_literal = ""
            for k in range(j):
                sum1 += round(pow(L[j][k], 2),digits)
                operation_literal += "("+str(L[j][k])+")^2"
                if j != i-1:
                    operation_literal += "+"
            print("The sum of (L[j][k])^2 is defined by:")
            print(operation_literal + " = " + str(sum1))
            L[j][j] = round(np.sqrt(A[j][j] - sum1),digits)
            print("L["+str(j)+"]["+str(j)+"]"+" = "+"(A["+str(j)+"]["+str(j)+"] - sum1 = "+str(A[j][j])+" - "+str(sum1) + " = "+str(L[j][j]))
        else:
            operation_literal = ""
            # Evaluating L(i, j)
            # using L(j, j)
            for k in range(j):
                sum1 += (L[i][k] *L[j][k])
                operation_literal += "("+str(L[i][k])+"*"+str(L[j][k])+")"
                if j != i-1:
                    operation_literal += "+"
            print("The sum of L[i][k]*L[j][k] is defined by:")
            print(operation_literal + " = " + str(sum1))
            if(L[j][j] > 0):
                L[i][j] = round(round(A[i][j] - sum1, digits) /L[j][j],digits)
                print("L[" + str(i) + "][" + str(j) + "] = (A["+str(i)+"]["+str(j)+"] - sum)/L["+str(j)+"]["+str(j)+"] = (" +str(A[i][j])+" - "+str(sum1)+" = "+str(L[i][j]))

The sum of (L[j][k])^2 is defined by:
 = 0
L[0][0] = (A[0][0] - sum1 = 9.0 - 0 = 3.0
The sum of L[i][k]*L[j][k] is defined by:
 = 0
L[1][0] = (A[1][0] - sum)/L[0][0] = (3.0 - 0 = 1.0
The sum of (L[j][k])^2 is defined by:
(1.0)^2+ = 1.0
L[1][1] = (A[1][1] - sum1 = 17.0 - 1.0 = 4.0
The sum of L[i][k]*L[j][k] is defined by:
 = 0
L[2][0] = (A[2][0] - sum)/L[0][0] = (3.0 - 0 = 1.0
The sum of L[i][k]*L[j][k] is defined by:
(1.0*1.0) = 1.0
L[2][1] = (A[2][1] - sum)/L[1][1] = (10.0 - 1.0 = 2.25
The sum of (L[j][k])^2 is defined by:
(1.0)^2+(2.25)^2+ = 6.0625
L[2][2] = (A[2][2] - sum1 = 11.0 - 6.0625 = 2.222
The sum of L[i][k]*L[j][k] is defined by:
 = 0
L[3][0] = (A[3][0] - sum)/L[0][0] = (4.0 - 0 = 1.3333
The sum of L[i][k]*L[j][k] is defined by:
(1.3333*1.0)+ = 1.3333
L[3][1] = (A[3][1] - sum)/L[1][1] = (5.0 - 1.3333 = 0.9167
The sum of L[i][k]*L[j][k] is defined by:
(1.3333*1.0)(0.9167*2.25) = 3.3958749999999998
L[3][2] = (A[3][2] - sum)/L[2][2] = (4.0 - 3.3958749999999998 = 0.2719
The sum 

In [8]:
print("Lower Triangular\t\tTranspose")
for i in range(dim):
        
    # Lower Triangular
    for j in range(dim):
        print(L[i][j], end = "\t")
    print("", end = "\t")
        
    # Transpose of
    # Lower Triangular
    for j in range(dim):
        print(L[j][i], end = "\t")
    print("")

Lower Triangular		Transpose
3.0	0.0	0.0	0.0		3.0	1.0	1.0	1.3333	
1.0	4.0	0.0	0.0		0.0	4.0	2.25	0.9167	
1.0	2.25	2.222	0.0		0.0	0.0	2.222	0.2719	
1.3333	0.9167	0.2719	3.2106		0.0	0.0	0.0	3.2106	
