In [3]:
# Import useful libs:
import numpy as np 
import sys

In [4]:
# Get the array dimensions:
print("Dimensions:")
dim = int(input("Insert number o variables of the system:"))
print(str(dim) + "," + str(dim))
#Get the round rule for the problem:
digits = int(input("Insert the number of digits after the decimal points:"))
print("Digits after the decimal points:")
print(digits)

Dimensions:
3,3
Digits after the decimal points:
3


In [5]:
# Create input and output
A = np.zeros((dim,dim))
L = np.zeros((dim,dim))

In [6]:
# Fill the A array:
for i in range(0, dim):
    for j in range(0,dim):
        A[i][j] = float(input("Enter value in position ("+str(i)+","+str(j)+")"))
print("A = " + str(A))

A = [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


In [7]:
def symmetric(array):
    x,y = array.shape
    if x != y:
        return False
    else:
        for i in range (0,x):
            for j in range (0,y):
                if A[i][j] != A[j][i]:
                    return False
    return True
positive = np.linalg.eigvals(A)
print(positive)
if np.all(positive > 0) and symmetric(A):
    print("True")
else:
    print("False")

[1.23477232e+02 1.88049805e-02 1.55039632e+01]
True


In [15]:
# Decomposing a matrix
# into Lower Triangular
for i in range(dim):
    for j in range(i + 1):
        sum1 = 0
        # sum1mation for diagnols
        if j == i:
            operation_literal = ""
            for k in range(j):
                sum1 += round(pow(L[j][k], 2),digits)
                operation_literal += "("+str(L[j][k])+")^2"
                if j != i-1:
                    operation_literal += "+"
            print("The sum of (L[j][k])^2 is defined by:")
            print(operation_literal + " = " + str(sum1))
            L[j][j] = round(np.sqrt(A[j][j] - sum1),digits)
            print("L["+str(j)+"]["+str(j)+"]"+" = "+"(A["+str(j)+"]["+str(j)+"] - sum1 = "+str(A[j][j])+" - "+str(sum1) + " = "+str(L[j][j]))
        else:
            operation_literal = ""
            # Evaluating L(i, j)
            # using L(j, j)
            for k in range(j):
                sum1 += (L[i][k] *L[j][k])
                operation_literal += "("+str(L[i][k])+"*"+str(L[j][k])+")"
                if j != i-1:
                    operation_literal += "+"
            print("The sum of L[i][k]*L[j][k] is defined by:")
            print(operation_literal + " = " + str(sum1))
            if(L[j][j] > 0):
                L[i][j] = round(round(A[i][j] - sum1, digits) /L[j][j],digits)
                print("L[" + str(i) + "][" + str(j) + "] = (A["+str(i)+"]["+str(j)+"] - sum)/L["+str(j)+"]["+str(j)+"] = (" +str(A[i][j])+" - "+str(sum1)+" = "+str(L[i][j]))

The sum of (L[j][k])^2 is defined by:
 = 0
L[0][0] = (A[0][0] - sum1 = 4.0 - 0 = 2.0
The sum of L[i][k]*L[j][k] is defined by:
 = 0
L[1][0] = (A[1][0] - sum)/L[0][0] = (12.0 - 0 = 6.0
The sum of (L[j][k])^2 is defined by:
(6.0)^2+ = 36.0
L[1][1] = (A[1][1] - sum1 = 37.0 - 36.0 = 1.0
The sum of L[i][k]*L[j][k] is defined by:
 = 0
L[2][0] = (A[2][0] - sum)/L[0][0] = (-16.0 - 0 = -8.0
The sum of L[i][k]*L[j][k] is defined by:
(-8.0*6.0) = -48.0
L[2][1] = (A[2][1] - sum)/L[1][1] = (-43.0 - -48.0 = 5.0
The sum of (L[j][k])^2 is defined by:
(-8.0)^2+(5.0)^2+ = 89.0
L[2][2] = (A[2][2] - sum1 = 98.0 - 89.0 = 3.0


In [19]:
print("Lower Triangular\t\tTranspose")
for i in range(dim):
        
    # Lower Triangular
    for j in range(dim):
        print(L[i][j], end = "\t")
    print("", end = "\t")
        
    # Transpose of
    # Lower Triangular
    for j in range(dim):
        print(L[j][i], end = "\t")
    print("")

Lower Triangular		Transpose
2.0	0.0	0.0		2.0	6.0	-8.0	
6.0	1.0	0.0		0.0	1.0	5.0	
-8.0	5.0	3.0		0.0	0.0	3.0	
